### ISSUE TITLE
Create a page for FAQs, About and Contact Us

### ISSUE THREAD

**Issue by vaishnavimecit** [Stevens-DSC/marketplace-web#5]
FAQs with general questions and answers.
About the team and project.
Contact us to send us emails on concerns, feedbacks, or more.

**Comment by justinoboyle** [comment]
The information for this doesn't have to be filled in. I think the best way to do this would be to make a "generic" text page that we can change at any time.

**Comment by Ookayleb** [comment]
@justinoboyle  Are we splitting up FAQ, About and Contact Us pages, or making them as one? Or is this undecided atm.

**Comment by Ookayleb** [comment]
Wasn't able to link the PR using the github ui to this issue but i made https://github.com/Stevens-DSC/marketplace-web/pull/18 feedback welcom
